### ISSUE TITLE
aplikasi.bat

### ISSUE THREAD

**Issue by datax-art** [mas-elkhanza/SIMRS-Khanza#102]
saya agus dari sekadau ingin bertanya
kenapa saya sudah mengikuti cara instalasi nya. tapi stuck di Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No toolkit found pas buka aplikasi.bat
saya download yg di web khanza. tidak ada jre nya, yg link ini https://drive.google.com/drive/folders/0ByL--Jg6bdF7RG1NSlVTT2ZPODg
dan disitu ada tutorial nya tapi berbeda. mohon bantuan nya
besar harapan saya untuk medapat balasan dari bapat atau ibu sekalian
terimakasih atas waktu nya

**Comment by mohammadrizki** [comment]
Mohon dapat dijelaskan:
1. OS yang digunakan
2. Java yang terinstal
3. Bagaimana langkah-langkah instalasi yang telah dilakukan.
Terima kasih

**Comment by datax-art** [comment]
untuk sekarang sudah bisa server nya di jalan kan
instal di windows 10
java jre-8u281-windows-x64

saya mau bertanya lagi
gimana cara nya agar komputer client bisa manggil simrs khanza
soalnya saya panggil dengan ip tidak bisa
dan di tutorial hanya ada penjelasan tentang instalasi saja
mohon bantuan nya

**Comment by ahliweb** [comment]
mas @datax-art menurut saya ini bukan issue terkait aplikasinya.
silahkan disampaikan melalui forum atau melalui pengguna lain.

dalam google drive tersebut sudha ada SDK java nya
jadi cukup install SDK dan kebutuhan lainnya insyaAlloh udah bisa berjalan

mohon dapat di close issue ini
terimakasih
