### ISSUE TITLE
CELAH keamanan Log4j

### ISSUE THREAD

**Issue by newholder** [mas-elkhanza/SIMRS-Khanza#105]
Saya mau nanya tentang keamanan aplikasi ini setelah ditemukannya celah keamanan pada library Log4j yang katanya bisa digunakan untuk mengambil alih console dan membocorkan semua info yang tersimpan di komputer. Apakah sudah ada fixnya. Apaan sudah aman dipakai?

**Comment by mas-elkhanza** [comment]
aman, kita sudah pakai 2.15 dan ke atas
