### ISSUE TITLE
Error initializing QuantumRenderer: no suitable pipeline found

### ISSUE THREAD

**Issue by utqinadhif** [mas-elkhanza/SIMRS-Khanza#109]
![image](https://user-images.githubusercontent.com/10701527/156861905-3e4c961b-0600-42c0-a58a-4b6bd823c449.png)

Error initializing QuantumRenderer: no suitable pipeline found

**Comment by mas-elkhanza** [comment]
copykan Lib bawaan simrs ke dalam folder bin java
