### ISSUE TITLE
tidak bisa membuka aplikasi.bat di windows

### ISSUE THREAD

**Issue by bastomiadi** [mas-elkhanza/SIMRS-Khanza#112]
tidak bisa membuka aplikasi.bat di windows.
yang sudah saya lakukan untuk instalasinya :
1. Install xampp yang ada di folder KhanzaHMSWindows yang sudah di extract
2. jalankan xampp nya dan sudah berjalan
3. install java jdk yang ada didalam folder KhanzaHMSWindows dua duanya
4. masuk phpmyadmin lalu import sik.sql, sik_bridging_lab.sql, sik_bridging_radiologi.sql
5. sukses import sql tidak ada error, lalu 
6. copy folder webapss hasil extract KhanzaHMSWindows ke C:/xampp/htdocs
7. lalu buka aplikasi.bat
8. tapi muncul error seperti pada cmd

![Screenshot_4](https://user-images.githubusercontent.com/13336571/168722813-c8565e57-cc07-4b99-96ac-14a4ef2546e6.png)

**Comment by bastomiadi** [comment]
sudah bisa, masalahnya ada pada versi java, harusnya cukup pakai yang versi bellsoft-jdk13.0.2+9-windows-amd64-full.msi saja.

**Comment by elhasbany** [comment]
maaf kak saya mau nanya, klo saya blum muncul cmd seperti berikut 
problemnya kira kira dmna ya
