### ISSUE TITLE
beberapa variabel di package bridging tidak terdeteksi

### ISSUE THREAD

**Issue by henryferniansa** [mas-elkhanza/SIMRS-Khanza#114]
dari kmrn saya utak atik msh blm nemu solusinya
di bawah ini hasilnya

![image](https://user-images.githubusercontent.com/110883850/183570229-f6c62c8c-7980-4363-88d0-dea2d4e375b2.png)

**Comment by RizkyHamdani21** [comment]
> dari kmrn saya utak atik msh blm nemu solusinya di bawah ini hasilnya
> 
> ![image](https://user-images.githubusercontent.com/110883850/183570229-f6c62c8c-7980-4363-88d0-dea2d4e375b2.png)

nah sama nih masalahnya #

**Comment by yanekaputra** [comment]
> dari kmrn saya utak atik msh blm nemu solusinya di bawah ini hasilnya
> 
> ![image](https://user-images.githubusercontent.com/110883850/183570229-f6c62c8c-7980-4363-88d0-dea2d4e375b2.png)

make netbeans berapa?

**Comment by henryferniansa** [comment]
netbeans 12

**Comment by henryferniansa** [comment]
> > dari kmrn saya utak atik msh blm nemu solusinya di bawah ini hasilnya
> > ![image](https://user-images.githubusercontent.com/110883850/183570229-f6c62c8c-7980-4363-88d0-dea2d4e375b2.png)
> 
> make netbeans berapa?

netbeans 12
