### ISSUE TITLE
Tidak bisa print saat di jalankan pada NetBeans IDE, tapi aman saat compile

### ISSUE THREAD

**Issue by ryanbekabe** [mas-elkhanza/SIMRS-Khanza#120]
https://github.com/mas-elkhanza/SIMRS-Khanza/blob/a2f97f21dc50c33527c922e6457180fd2b396000/src/rekammedis/RMPenilaianAwalKeperawatanRalan.java#L3321

Report Can't view because : net.sf.jasperreports.engine.fill.JRExpressionEvalException: Error evaluating expression for source text: ($F{status_psiko}.equals("Lain-lain") ? Boolean.FALSE:Boolean.TRUE)

**Comment by mas-elkhanza** [comment]
folder reportnya dicek dulu
