### ISSUE TITLE
Lisensi proyek ini TIDAK open-source.

### ISSUE THREAD

**Issue by MikuAuahDark** [mas-elkhanza/SIMRS-Khanza#128]
https://github.com/mas-elkhanza/SIMRS-Khanza/blob/master/lisensi.txt

Proyek ini lebih cocok dikatakan "sumber tersedia" dibanding "open source". Kenapa? Karena open-source berarti dapat digunakan baik untuk tujuan non-komersil dan tujuan komersil. Tetapi, jika dituliskan "_open source_" tetapi ada batasan pada penggunaan komersil, maka tidak bisa disebut "open source". Hal ini bisa _menyesatkan_ definisi open source itu sendiri.

Saran saya adalah salah satu dari 3 berikut:
1. Hapuskan kata "open source".
> Software ini adalah Software Menejemen Rumah Sakit/Klinik/Puskesmas yang gratis dan boleh digunakan siapa saja tanpa dikenai biaya apapun.
2. Ubah kata "open source" mejadi "sumber tersedia"
> Software ini adalah Software Menejemen Rumah Sakit/Klinik/Puskesmas yang gratis, **sumber tersedia**, dan boleh digunakan siapa saja tanpa dikenai biaya apapun.
3. Gunakan lisensi [CC-BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/).

**Comment by iyansr** [comment]
up

**Comment by guangrei** [comment]
kalau dari `README.TXT` disebutkan menggunakan lisensi Aladdin Free Public License (AFPL) tapi tetap tidak compatible dengan project opensource.


> is aladdin free public license an open source license?

```
The Aladdin Free Public License (AFPL) is a free software license, but it is not an open source license.

An open source license is a software license that gives users the right to run, study, share, and modify the software. The AFPL does not allow for the sale of the software, which is a restriction that is not found in most open source licenses.

The AFPL was created by L. Peter Deutsch for his Ghostscript PostScript language interpreter. Deutsch felt that the GNU General Public License (GPL), which is a popular open source license, unfairly prevented developers of useful software from being compensated proportionately when others profit financially from their work. The AFPL was designed to address this concern by allowing developers to charge for the distribution of the software, but not for the software itself.

The AFPL is still used by some software projects, but it is not as popular as other open source licenses. Some of the reasons for this include the restriction on selling the software, and the fact that it is not as well-known as other licenses.

In conclusion, the Aladdin Free Public License is a free software license, but it is not an open source license. It is a more restrictive license that allows developers to charge for the distribution of the software, but not for the software itself.
```
