### ISSUE TITLE
Error cannot find symbol headers

### ISSUE THREAD

**Issue by fredyna** [mas-elkhanza/SIMRS-Khanza#77]
Created dir: /Users/fredd/data/rsui/SIMRS-Khanza/build/generated-sources/ap-source-output
Compiling 762 source files to /Users/fredd/data/rsui/SIMRS-Khanza/build/classes
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareCariKegiatanKelompok.java:356: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareCekFaskesAlihRawat.java:508: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareCekFaskesSubspesialis.java:522: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareCekReferensiSubspesialis.java:432: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareCekReferensiSarana.java:345: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareCekReferensiSpesialis.java:345: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareCekFaskesThalasemia.java:592: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareCekReferensiPoli.java:352: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareCekReferensiDokter.java:343: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareCekReferensiKesadaran.java:343: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareCekReferensiKhusus.java:343: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareCekReferensiObat.java:352: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareCekReferensiPenyakit.java:349: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareCekReferensiProvider.java:345: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareCekReferensiStatusPulang.java:345: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareCekReferensiTindakan.java:369: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareCekRujukan.java:349: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareClubProlanis.java:326: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareDataPemberianObat.java:536: error: cannot find symbol
                headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareDataPemberianTindakan.java:616: error: cannot find symbol
                    headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareDataPemberianTindakan.java:683: error: cannot find symbol
                    headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareDataPendaftaran.java:2568: error: cannot find symbol
                    headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareDataPendaftaran.java:2720: error: cannot find symbol
                        headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareDataPendaftaran.java:2819: error: cannot find symbol
                        headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareDataPendaftaran.java:3065: error: cannot find symbol
                    headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareDataPendaftaran.java:3541: error: cannot find symbol
                        headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareDataPendaftaran.java:4612: error: cannot find symbol
            headers2.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareDataPendaftaran.java:4776: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareDataPendaftaran.java:4840: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareDataPendaftaran.java:4904: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareKegiatanKelompok.java:986: error: cannot find symbol
                headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareKegiatanKelompok.java:1069: error: cannot find symbol
                    headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareKegiatanKelompok.java:1134: error: cannot find symbol
                    headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareKegiatanKelompok.java:1161: error: cannot find symbol
                headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareKegiatanKelompok.java:1382: error: cannot find symbol
                headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCareNIK.java:242: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCarePeserta.java:242: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/PCarePesertaKegiatanKelompok.java:558: error: cannot find symbol
                headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/bridging/tessaja5.java:27: error: cannot find symbol
        System.out.println("X-Authorization:Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/inventory/DlgCariObat.java:4014: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/inventory/DlgCariObat2.java:4129: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/keuangan/DlgCariPerawatanRalan.java:1525: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
/Users/fredd/data/rsui/SIMRS-Khanza/src/keuangan/DlgCariPerawatanRanap.java:1858: error: cannot find symbol
            headers.add("X-Authorization","Basic "+Base64.encodeBase64String(otorisasi.getBytes()));
  symbol:   method encodeBase64String(byte[])
  location: class Base64
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
43 errors
/Users/fredd/data/rsui/SIMRS-Khanza/nbproject/build-impl.xml:1109: The following error occurred while executing this line:
/Users/fredd/data/rsui/SIMRS-Khanza/nbproject/build-impl.xml:410: Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 2 minutes 55 seconds)

**Comment by ahliwebcom** [comment]
itu masalah pada environment Anda
untuk mudahnya bisa menggunakan bellsoft java 12 jdk dan netbeans 11
kalo udah solve tlg ditutup issue nya
