### ISSUE TITLE
[BUG] Webapp Pendaftaran Pasien SQL Injection

### ISSUE THREAD

**Issue by f1dz** [mas-elkhanza/SIMRS-Khanza#78]
Pada halaman login pendaftaran pasien [webapps/pendaftaran/login.php](https://github.com/mas-elkhanza/SIMRS-Khanza/blob/master/webapps/pendaftaran/login.php) rawan SQL Injection

**Comment by ahliwebcom** [comment]
sudah ada function filter, atau silahkan ditambahin filter apabila masih ada yg kurang

**Comment by f1dz** [comment]
Maksudnya filter input bawaan PHP?
Alangkah lebih baik menggunakan Prepared Statements. Dan akan lebih baik lagi menurut saya jika menggunakan framework, kita sudah tidak perlu pusing dengan security. Selain form tsb sebenarnya masih ada banyak yg rawan SQL injection.

**Comment by ontzuevanhussen** [comment]
Jangan pakai framework lah, emang mau bikin skripsi?

**Comment by f1dz** [comment]
@ontzuevanhussen kalau boleh tahu ada masalah apa dengan framework? Dari pada aplikasi kita rawan diserang dan kita tidak punya waktu untuk mengamankan aplikasi kita, tidak ada salahnya kok menggunakan framework. Tidak ada hubungannya juga dengan skripsi. Dan saya sekarang tidak tahu juga, lagi ngomong sama developer atau user.

**Comment by f1dz** [comment]
Karena sepertinya kita tidak konsen dengan security, lebih baik saya close saja ya
