### ISSUE TITLE
Label & Barcode, cmd

### ISSUE THREAD

**Issue by ariefkurnia** [mas-elkhanza/SIMRS-Khanza#79]
Selamat Pagi..
saya ingin menanyakan solusi terhadap masalah yang saya alami. 
di RS kami menggunakan barcode perawatan 1 untuk label identitas pasien, pasien bisa dicetak barcode perawatan 1 jika sudah ada di menu registrasi. namun, yang terjadi di lapangan, barcode tercetak namun pasien tidak ada di menu registrasi.

dan ditambah ada notif seperti ini jika menjalan aplikasi.bat
log4j:WARN No appenders could be found for logger (org.springframework.util.ClassUtils).
log4j:WARN Please initialize the log4j system properly.

**Comment by mas-elkhanza** [comment]
Cek di IGD, masuk gak

**Comment by ahliwebcom** [comment]
> log4j:WARN No appenders could be found for logger (org.springframework.util.ClassUtils).
> log4j:WARN Please initialize the log4j system properly.
ini tidak masalah

kl udah solve tlg di close issue nya ya mas
