### ISSUE TITLE
[HELP WANTED] tidak bisa input pasien rawat inap

### ISSUE THREAD

**Issue by jimmyferiawan** [mas-elkhanza/SIMRS-Khanza#95]
> Notifikasi : com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect data value: '0000-00-00' for cloumn 

`sik`.`kamar_inap`.`tgl_keluar` at row 1
![error input rawat inap](https://user-images.githubusercontent.com/27266334/107057566-33052600-6806-11eb-8dc2-7f823a30fb14.PNG)
![console khanza](https://user-images.githubusercontent.com/27266334/107057574-34365300-6806-11eb-9546-492adeaf7515.PNG)

**Comment by mas-elkhanza** [comment]
sql modenya juragan. Pakai saja xampp bawaan simrs khanza
